# Generated by Django 5.1.5 on 2025-02-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About sahifasi'},
        ),
    ]
