# Generated by Django 5.1.5 on 2025-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(),
        ),
    ]
