# Generated by Django 5.1.5 on 2025-02-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('token', models.TextField()),
                ('user_id_list', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Telegram Bot sozlamalari',
            },
        ),
    ]
